# Generated by Django 3.2 on 2021-05-16 17:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                ("reception_time", models.DateTimeField()),
                ("location", models.JSONField(primary_key=True, serialize=False)),
                ("units", models.CharField(max_length=11)),
                (
                    "forecasts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), size=None
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                ("time", models.DateTimeField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20)),
                ("temperature", models.FloatField()),
                ("pressure", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("direction", models.CharField(max_length=3)),
                ("humidity", models.IntegerField()),
                ("rain", models.FloatField()),
                ("snow", models.FloatField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(max_length=60, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
