# Generated by Django 3.2 on 2021-05-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forecast",
            old_name="forecast",
            new_name="forecasts",
        ),
    ]
