# Generated by Django 3.2 on 2021-05-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_rename_forecast_forecast_forecasts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="forecasts",
            field=models.ManyToManyField(blank=True, to="weather.Weather"),
        ),
    ]
