# Generated by Django 3.2 on 2021-04-26 14:18

import datetime

from django.db import migrations


def add_data(apps, schema_editor):
    """Add single row to each table."""
    hw = apps.get_model("hw12", "Homework")(
        text="Foo", deadline=datetime.timedelta(days=1)
    )
    student = apps.get_model("hw12", "Student")(last_name="Rybakov", first_name="Denis")
    teacher = apps.get_model("hw12", "Teacher")(
        last_name="Shevyakhova", first_name="Arina"
    )
    hw_result = apps.get_model("hw12", "HomeworkResult")(
        solution="Solved", homework=hw, author=student
    )
    for data in hw, student, teacher, hw_result:
        data.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hw12", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
